services:
  superset:
    image: ai12_superset:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=KF9MCWa6sg3AYeCZ8KkIXKrNK4f1yBk30mwvJhaKidvL2HkJ+vIJfJJo
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - MAPBOX_API_KEY=pk.eyJ1IjoiYWdyaW5pbiIsImEiOiJjbWZreHlhcnIwMjFnMm1zNnBpaW91M2pvIn0.56vxzoKVrYvnZtM_j3DNog
      - REDIS_URL=redis://redis:6379/0
      - SUPERSET_HOME=/app/superset_home
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    volumes:
      - ./superset_config.py:/app/superset_config.py
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    restart: always

volumes:
  superset_db_data: